#ifndef FILESYSTEM_STATUS_H
#define FILESYSTEM_STATUS_H

typedef enum{FILE_NOT_OPENED, FILE_NOT_FOUND, FILE_SIZE_ERROR, FILE_READING_ERROR, FILE_CLOSING_ERROR,
    FILE_HEADER_ERROR, FILE_SUCCESS} FileSystemResultMessage;


#endif
