#ifndef PLATFORM_DEFINES_H_
#define PLATFORM_DEFINES_H_

#define PLATFORM_HALYAVINO_ZERO 1
#define PLATFORM_HOST 0

#define PLATFORM_TYPE PLATFORM_HALYAVINO_ZERO

#define LED_CHANNELS_COUNT 6
#define GPIO_CHANNELS_COUNT 8

#endif //PLATFORM_DEFINES_H_
